image: rocker/verse

test:
  script:
    - R -e "install.packages(c('janitor'))"
    - R -e "sessionInfo()"
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-manual --no-build-vignettes --as-cran
