image: rocker/verse

test:
  script:
    - R -e "sessionInfo()"
    - "Rscript -e \"deps <- remotes::dev_package_deps(dependencies = NA)$package; remotes::install_deps(dependencies = TRUE); ip <- as.data.frame(installed.packages())$Package; message('deps = ', class(deps), ', ip = ', class(ip));}\""
    - R CMD build .
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --as-cran
