image: rocker/verse

test:
  script:
    - R -e "sessionInfo()"
    - R -e "deps <- remotes::dev_package_deps(dependencies = NA);remotes::install_deps(dependencies = TRUE);"
    - R -e "if (!all(deps$package %in% installed.packages())) { message('missing: ', paste(setdiff(deps$package, installed.packages()), collapse=', ')); q(status = 1, save = 'no')}"
    - R CMD build .
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --as-cran
