language: r
sudo: false
cache: packages

matrix:
  include:
    - name: release
      r: release
      r_check_args: --as-cran --no-build-vignettes
    - name: devel
      r: devel
      r_check_args: --as-cran --no-build-vignettes --use-valgrind
      env:
        - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
      addons:
        apt:
          packages:
            - valgrind

r_build_args: --no-resave-data --no-build-vignettes

before_script:
  - if ! test -d inst/doc; then mkdir inst/doc; fi
  - cp -R doc/* inst/doc/
  - cp -R Meta/* inst/doc/
