language: R
sudo: required

cache: packages

r_packages:
  - devtools
  - rmarkdown

install:
- R -e 'devtools::install_deps(dep = T)'

script:
- R --no-save --no-restore CMD build --no-resave-data --no-build-vignettes .
- R --no-save --no-restpre CMD check --as-cran --no-manual --timings *tar.gz 
