language: r
sudo: false
cache: packages

matrix:
  include:
    - name: release
      r: release
      r_check_args: --as-cran
    - name: devel
      r: devel
      r_check_args: --as-cran --use-valgrind
      env:
        - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
      addons:
        apt:
          packages:
            - valgrind
      script:
        - mkdir inst/doc
        - cp -R doc/ inst/doc/
        - cp -R Meta/ inst/doc/
        - R CMD build --no-resave-data --no-build-vignettes .
        - travis_wait R CMD check "${PKG_TARBALL}" --as-cran --no-build-vignettes; CHECK_RET=$?

r_build_args: --no-resave-data
