// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// history_lookup
int history_lookup(IntegerVector x);
RcppExport SEXP fsm_history_lookup(SEXP xSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP );
        int __result = history_lookup(x);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// fitnessCPP
IntegerVector fitnessCPP(IntegerVector action_vec, IntegerMatrix state_mat, IntegerMatrix covariates, IntegerVector period);
RcppExport SEXP fsm_fitnessCPP(SEXP action_vecSEXP, SEXP state_matSEXP, SEXP covariatesSEXP, SEXP periodSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerVector >::type action_vec(action_vecSEXP );
        Rcpp::traits::input_parameter< IntegerMatrix >::type state_mat(state_matSEXP );
        Rcpp::traits::input_parameter< IntegerMatrix >::type covariates(covariatesSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type period(periodSEXP );
        IntegerVector __result = fitnessCPP(action_vec, state_mat, covariates, period);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
