// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fitnessC
IntegerVector fitnessC(IntegerVector action_vec, IntegerMatrix state_mat, IntegerMatrix x);
RcppExport SEXP fsm_fitnessC(SEXP action_vecSEXP, SEXP state_matSEXP, SEXP xSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerVector >::type action_vec(action_vecSEXP );
        Rcpp::traits::input_parameter< IntegerMatrix >::type state_mat(state_matSEXP );
        Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP );
        IntegerVector __result = fitnessC(action_vec, state_mat, x);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
