# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fitness function for Prisoner Dilemma game data.
#'
#' @param action_vec Integer Vector.
#' @param state_mat IntegerMatrix.
#' @param x IntegerMatrix.
#'
#' @export
fitnessC <- function(action_vec, state_mat, x) {
    .Call('fsm_fitnessC', PACKAGE = 'fsm', action_vec, state_mat, x)
}

