# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

history_lookup <- function(x) {
    .Call('fsm_history_lookup', PACKAGE = 'fsm', x)
}

#' Fitness Function in C++
#'
#' @param action_vec Integer Vector.
#' @param state_mat Integer Matrix.
#' @param covariates Integer Matrix.
#' @param period Integer Vector.
#'
#' @export
#' @useDynLib fsm
#' @importFrom Rcpp sourceCpp
fitnessCPP <- function(action_vec, state_mat, covariates, period) {
    .Call('fsm_fitnessCPP', PACKAGE = 'fsm', action_vec, state_mat, covariates, period)
}

